# Generated by Django 5.2.3 on 2025-06-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteamprilozenie', '0002_prediction_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='smoking_status',
            field=models.CharField(choices=[('never smoked', 'Не курит'), ('formerly smoked', 'Бывший курильщик'), ('smokes', 'Курит')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('Yes', 'Состоял/Состою в браке'), ('No', 'В браке не состоял никогда')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='work_type',
            field=models.CharField(choices=[('Private', 'Частный сектор'), ('Self-employed', 'Самозанятый'), ('Govt_job', 'Госслужащий'), ('children', 'Сижу с детьми'), ('Never_worked', 'Не работал(а)')], max_length=20),
        ),
    ]
